### ISSUE TITLE
Tabellerkolumner i databasen är lowercase vilket gör att Gson inte kan skapa objektet korrekt. 

### ISSUE THREAD

**Issue by henninghall** [Rovanion/AinWebServer#9]
Förslag på lösningar:
1. Fixa uppercase på kolumnerna i databasen på något sätt.
2. Skapa en funktion som översätter lowercase till uppercase på rätt ställen / mappar de olika tabellerna. Antingen på server eller klientsidan.
3. Kör lowercase på Case-objektet lokalt (och då även automatiskt tabellkolumnerna lokalt)

**Comment by Rovanion** [comment]
Du menar att variabelnamnen i Case-objektet på webbservern inte är camelcase men att dom är det på androidappen?

**Comment by henninghall** [comment]
Ja precis, och eftersom de blir lowercase i json (tex http://christian.cyd.liu.se:1337/case/1/1) så skapar gson inte ett korrekt objekt då den inte förstår att tex modificationtime = modificationTime

**Comment by Rovanion** [comment]
Den bästa lösningen på det här är om någon lyckas confa mybatis-generator så att den respekterar camel-casing:en i databasfältens namn.

**Comment by Rovanion** [comment]
Cleanup.
